import fs from 'node:fs';
import path from 'node:path';
const NL = String.fromCharCode(10);

// Values come from the data layer, not from me retyping them — the whole reason
// these listings are wrong is that someone once transcribed a figure by hand.
import { SITE, PACKAGES } from '../../src/data/packages.js';

const inr = (n) => '₹' + Number(n).toLocaleString('en-IN');
const charDham = PACKAGES.find((p) => /^Char Dham Yatra Package — 9 Nights 10 Days/.test(p.name));
const heli = PACKAGES.find((p) => /Char Dham Yatra by Helicopter/.test(p.name));
const senior = PACKAGES.find((p) => /Senior Citizen Special/.test(p.name));

// Local date, not toISOString() — IST midnight converts back to the previous day.
const d = new Date();
const today = d.getFullYear() + '-' + String(d.getMonth()+1).padStart(2,'0') + '-' + String(d.getDate()).padStart(2,'0');

const L = [
  '# Listing corrections — do all three in one sitting',
  '',
  'Generated ' + today + ' from `src/data/packages.js` and `src/data/social.js`.',
  'Regenerate rather than editing by hand.',
  '',
  '## Why together',
  '',
  'Google, Bing and TripAdvisor all publish the same wrong opening hours, and two',
  'of the three spell the address the same wrong way. Two independent facts wrong',
  'identically across three platforms is one seeding source, not three mistakes.',
  'Fixing one and leaving the others means the wrong version stays authoritative',
  'on two surfaces — and Bing feeds Copilot and a share of ChatGPT, so it',
  'propagates into AI answers about the business.',
  '',
  '## The canonical values — paste these, do not retype',
  '',
  '```',
  'Name      Shiv Ganga Travels',
  'Address   ' + SITE.address,
  'Phone     ' + SITE.phone,
  'Email     ' + SITE.email,
  'Website   ' + SITE.baseUrl,
  'Hours     ' + SITE.hoursHuman + ' daily (all seven days)',
  'Founded   ' + SITE.established,
  '```',
  '',
  'Spelling that matters: **Bhupatwala**, not Bhoopatwala. **Saptrishi Road**, not',
  'Saptsarover Road. Never write bare "Haridwar" without the full address — the',
  'name is shared with at least three other Indian operators, one of them also in',
  'Haridwar.',
  '',
  'Price anchor: **' + inr(charDham.price.discounted) + ' per person** for Char Dham 9N/10D. Not ' + inr(charDham.price.original) + ', not',
  '₹19,500, not ₹21,000. The senior package is ' + inr(senior.price.discounted) + ' for 12N/13D and the',
  'helicopter is ' + inr(heli.price.discounted) + ' — those are different products, do not let either be',
  'attached to the 9N/10D label.',
  '',
  '---',
  '',
  '## 1. TripAdvisor — start here, it is the shortest',
  '',
  'Owner page:',
  '`https://www.tripadvisor.com/Owners-g616028-d34343558-Shiv_Ganga_Travels-Haridwar_Haridwar_District_Uttarakhand.html`',
  '',
  'Already claimed. Press **Verify identity** first — nothing below is editable',
  'until that clears, and only you can do it.',
  '',
  '| Field | Currently | Change to |',
  '|---|---|---|',
  '| About text | "packages from ₹19,500 per person" | "packages from ' + inr(charDham.price.discounted) + ' per person" |',
  '| Hours | 7:00 AM – 9:00 PM | ' + SITE.hoursHuman + ', all seven days |',
  '| Address | ...Bhoopatwala... | ' + SITE.address + ' |',
  '| Contact block | empty | ' + SITE.phone + ' · ' + SITE.email + ' · ' + SITE.baseUrl + ' |',
  '',
  'Worth doing while you are in: you are #41 of 96 Tours & Activities in Haridwar',
  'on a single review. Asking recent pilgrims for a TripAdvisor review moves that',
  'more than any field edit will.',
  '',
  '---',
  '',
  '## 2. Google Business Profile — most traffic, most fiddly',
  '',
  '`https://business.google.com/` → Edit profile',
  '',
  'Edit by hand. The dialog does not accept automated input reliably.',
  '',
  '| Where | Currently | Change to |',
  '|---|---|---|',
  '| Business information → Hours | 07:00–21:00, seven days | ' + SITE.hours.opens + '–' + SITE.hours.closes + ', seven days |',
  '| Business information → Location | Bhoopatwala, + "Motichur Range" | ' + SITE.address + ' |',
  '| **Edit products** (not Business information) | ₹21,000 on the 9N/10D package | ' + inr(charDham.price.discounted) + ' |',
  '| Business information → About | Opening date 10 Aug 2017 | ' + SITE.established + ', to match the description that already says "since ' + SITE.established + '" |',
  '',
  'The ₹21,000 is the senior 12N/13D price sitting on the 9N/10D label. It shows',
  'in the Booking options module beside "Instant confirmation", which is the worst',
  'place on the internet to carry a wrong price.',
  '',
  'Consider **Special hours** rather than one flat year-round setting — Char Dham',
  'is a May–November business and the office may genuinely run longer in season.',
  '',
  '---',
  '',
  '## 3. Bing Places — claim first',
  '',
  '`https://www.bingplaces.com/`',
  '',
  'A verified listing already exists. Claim it — do **not** create a second one, or',
  'you will be competing with yourself on a platform that feeds AI answers.',
  '',
  '| Field | Currently | Change to |',
  '|---|---|---|',
  '| Address | "Saptsarover Road, Hardwar, UK" | ' + SITE.address + ' |',
  '| Hours | 07:00–21:00 | ' + SITE.hours.opens + '–' + SITE.hours.closes + ' |',
  '',
  'Saptsarover is a different road from Saptrishi. Phone, website and description',
  'are already correct — leave them alone.',
  '',
  '---',
  '',
  '## After',
  '',
  'Add a row to the table in `directory-submissions.md` for each one, with the date',
  'and what you changed. That file is the only record of where these values have',
  'been pasted, and its absence is why three listings went stale unnoticed.',
  '',
  'Then tell me and I will re-read all three and confirm they match the site.',
  '',
];

const out = path.join('outreach', 'LISTING-CORRECTIONS.md');
fs.writeFileSync(out, L.join(NL) + NL);
console.log('wrote ' + out + ' (' + L.length + ' lines)');
console.log('price anchor used: ' + inr(charDham.price.discounted));
console.log('hours used: ' + SITE.hoursHuman + ' / ' + SITE.hours.opens + '-' + SITE.hours.closes);
