/* Footer link architecture — every route preserved verbatim.
   This is the site's internal-link backbone; do not prune it. */

import { LANGUAGE_PAGES } from '@/data/languages';

export const COLS = [
  { heading:'Char Dham Packages', links:[
    {l:'Char Dham Yatra 2026',       h:'/char-dham-yatra'},
    {l:'Char Dham Guide 2026',       h:'/blog/char-dham-guide'},
    {l:'Classic 9N/10D',             h:'/packages/char-dham-yatra-9n-10d-haridwar'},
    {l:'Deluxe 11N/12D',             h:'/packages/char-dham-yatra-11n-12d-haridwar'},
    {l:'Helicopter 5N/6D',           h:'/char-dham-helicopter'},
    {l:'Senior Special 12N/13D',     h:'/packages/char-dham-yatra-senior-citizen-12n-13d'},
    {l:'From Delhi',                 h:'/char-dham-yatra-from-delhi'},
    {l:'From Noida',                 h:'/char-dham-yatra-from-noida'},
    {l:'From Mumbai',                h:'/char-dham-yatra-from-mumbai'},
    {l:'From Bangalore',             h:'/char-dham-yatra-from-bangalore'},
  ]},
  { heading:'Single & Do Dham', links:[
    {l:'Kedarnath Yatra',            h:'/kedarnath-yatra'},
    {l:'Kedarnath Package 3N/4D',    h:'/kedarnath-tour-package'},
    {l:'Badrinath Package 2N/3D',    h:'/badrinath-tour-package'},
    {l:'Badrinath Yatra',            h:'/badrinath-yatra'},
    {l:'Gangotri Yatra',             h:'/gangotri-yatra'},
    {l:'Yamunotri Yatra',            h:'/yamunotri-yatra'},
    {l:'Do Dham Yatra',              h:'/do-dham-yatra'},
    {l:'Teen Dham Yatra',            h:'/teen-dham-yatra'},
    {l:'Panch Kedar Yatra',          h:'/panch-kedar-yatra'},
    {l:'Panch Badri Yatra',          h:'/panch-badri-yatra'},
    {l:'Chopta & Tungnath',          h:'/chopta-tungnath'},
    {l:'Uttarakhand Tours',          h:'/uttarakhand-tour-packages'},
    {l:'Valley of Flowers',          h:'/packages/valley-of-flowers-hemkund-sahib-5n-6d'},
  ]},
  { heading:'Cabs & Transport', links:[
    {l:'All Uttarakhand Cabs',         h:'/cabs'},
    {l:'Char Dham Cab Booking',       h:'/char-dham-yatra-cab-booking'},
    {l:'Cabs from Haridwar',          h:'/cabs/from/haridwar'},
    {l:'Cabs to Kedarnath',           h:'/cabs/to/kedarnath'},
    {l:'Cabs to Badrinath',           h:'/cabs/to/badrinath'},
    {l:'Haridwar → Kedarnath Cab',    h:'/cabs/haridwar-to-kedarnath-cab'},
    {l:'Delhi → Haridwar Cab',        h:'/cabs/delhi-to-haridwar-cab'},
  ]},
  { heading:'Guides & Tools', links:[
    {l:'2026 New Rules',             h:'/blog/char-dham-yatra-2026-new-rules'},
    {l:'Cost Calculator',            h:'/char-dham-yatra-cost-calculator'},
    {l:'Route Map',                  h:'/char-dham-yatra-route-map'},
    {l:'Kedarnath Trek Guide',       h:'/blog/kedarnath-trek-guide'},
    {l:'Helicopter Booking',         h:'/blog/kedarnath-helicopter-booking'},
    {l:'Packing List',               h:'/blog/char-dham-yatra-packing-list'},
    {l:'Cost Breakdown',             h:'/blog/char-dham-yatra-cost'},
    {l:'Registration Guide',         h:'/blog/char-dham-yatra-registration'},
    {l:'Best Time to Visit',         h:'/blog/best-time-char-dham'},
    {l:'All Blog Posts',             h:'/blog'},
  ]},
  { heading:'Temples & Weather', links:[
    {l:'Kedarnath Temple Guide',     h:'/kedarnath-temple'},
    {l:'Badrinath Temple Guide',     h:'/badrinath-temple'},
    {l:'Gangotri Temple Guide',      h:'/gangotri-temple'},
    {l:'Yamunotri Temple Guide',     h:'/yamunotri-temple'},
    {l:'Dhari Devi Temple',          h:'/dhari-devi-temple'},
    {l:'Devprayag Sangam',           h:'/devprayag'},
    {l:'Rudraprayag Sangam',         h:'/rudraprayag'},
    {l:'Kainchi Dham',               h:'/kainchi-dham'},
    {l:'Kedarnath Height & Facts',   h:'/kedarnath-height'},
    {l:'Kedarnath Weather',          h:'/kedarnath-weather'},
    {l:'Badrinath Weather',          h:'/badrinath-weather'},
    {l:'Gangotri Weather',           h:'/gangotri-weather'},
    {l:'Yamunotri Weather',          h:'/yamunotri-weather'},
  ]},
  { heading:'How to Reach', links:[
    {l:'How to Reach Kedarnath',     h:'/blog/how-to-reach-kedarnath'},
    {l:'How to Reach Badrinath',     h:'/how-to-reach-badrinath'},
    {l:'How to Reach Gangotri',      h:'/how-to-reach-gangotri'},
    {l:'How to Reach Yamunotri',     h:'/how-to-reach-yamunotri'},
    {l:'Kedarnath Hotels',           h:'/kedarnath-hotels'},
    {l:'Badrinath Hotels',           h:'/badrinath-hotels'},
    {l:'Emergency Contacts',         h:'/char-dham-yatra-emergency-contacts'},
    {l:'How to Reach Haridwar',      h:'/how-to-reach-haridwar'},
    {l:'Taxi Service in Haridwar',   h:'/taxi-service-in-haridwar'},
    {l:'Dehradun Airport → Haridwar',h:'/dehradun-airport-to-haridwar-taxi'},
  ]},
  { heading:'Distances & On-Route', links:[
    {l:'Haridwar → Badrinath',       h:'/haridwar-to-badrinath-distance'},
    {l:'Haridwar → Gangotri',        h:'/haridwar-to-gangotri-distance'},
    {l:'Haridwar → Yamunotri',       h:'/haridwar-to-yamunotri-distance'},
    {l:'Delhi → Kedarnath',          h:'/delhi-to-kedarnath-distance'},
    {l:'Gangotri → Yamunotri',       h:'/gangotri-to-yamunotri-distance'},
    {l:'Altitude Sickness Guide',    h:'/altitude-sickness-char-dham'},
    {l:'Mobile Network Coverage',    h:'/char-dham-yatra-mobile-network'},
    {l:'Food on the Yatra',          h:'/char-dham-yatra-food-guide'},
  ]},
  { heading:'Before You Book', links:[
    {l:'How to Choose an Operator',  h:'/how-to-choose-char-dham-tour-operator'},
    {l:'Where to Book — Compared',   h:'/char-dham-yatra-booking-sites-compared'},
    {l:'Helicopter Booking Guide',   h:'/char-dham-helicopter-booking-guide'},
    {l:'Char Dham Yatra Scams',      h:'/char-dham-yatra-scams'},
    {l:'Temple & Mandir Groups',     h:'/char-dham-yatra-for-temple-groups'},
    {l:'Corporate Booking',          h:'/char-dham-yatra-corporate-booking'},
  ]},
  { heading:'Winter Char Dham', links:[
    {l:'Winter Char Dham Yatra',     h:'/winter-char-dham-yatra'},
    {l:'Omkareshwar, Ukhimath',      h:'/ukhimath'},
    {l:'Narsingh Temple, Joshimath', h:'/joshimath-narsingh-temple'},
    {l:'Mukhba — Ganga’s Seat', h:'/mukhba-gangotri-winter-seat'},
    {l:'Kharsali — Yamuna’s Seat', h:'/kharsali-yamunotri-winter-seat'},
    {l:'Kedarnath Doli Yatra',       h:'/kedarnath-doli-yatra'},
    {l:'Auli Skiing',                h:'/auli-skiing-package'},
  ]},
  { heading:'Haridwar Darshan', links:[
    {l:'Places to Visit in Haridwar',h:'/haridwar-sightseeing-places'},
    {l:'Har Ki Pauri & Ganga Aarti', h:'/har-ki-pauri-guide'},
    {l:'Mansa Devi Temple',          h:'/mansa-devi-temple'},
    {l:'Chandi Devi Temple',         h:'/chandi-devi-temple'},
    {l:'Daksh Mahadev, Kankhal',     h:'/daksh-mahadev-temple'},
    {l:'Maya Devi Temple',           h:'/maya-devi-temple'},
    {l:'Shantikunj Ashram',          h:'/shantikunj-haridwar-guide'},
    {l:'Patanjali Yogpeeth',         h:'/patanjali-yogpeeth-haridwar'},
    {l:'Kumbh Mela 2027',            h:'/kumbh-mela-haridwar'},
    {l:'Hotels in Haridwar',         h:'/haridwar-hotels'},
    {l:'Neelkanth Mahadev',          h:'/neelkanth-mahadev-temple'},
    {l:'Triveni Ghat, Rishikesh',    h:'/triveni-ghat-rishikesh'},
  ]},
  { heading:'Company', links:[
    {l:'About Us',                   h:'/about'},
    {l:'Contact Us',                 h:'/contact'},
    {l:'All Packages',               h:'/packages'},
    {l:'Online Puja Booking',        h:'/online-puja-booking'},
    {l:'Senior Citizen Package',     h:'/blog/senior-citizen-char-dham'},
    {l:'Leave a Review',             h:'/review'},
    {l:'Site Map',                   h:'/sitemap-page'},
    {l:'Cancellation Policy',        h:'/cancellation-policy'},
    {l:'Privacy Policy',             h:'/privacy-policy'},
    {l:'Terms & Conditions',         h:'/terms-and-conditions'},
  ]},
];

export const LANGUAGE_COL = {
  heading: 'Char Dham in Your Language',
  links: LANGUAGE_PAGES.map(l => ({ l: `${l.native} · ${l.label}`, h: `/${l.slug}` })),
};

